server:
  port: 8827
Spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:ddbquery.db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/static/
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,templates/**Dialect